In [ ]:
"""
Gen AI course
Assignment- NumPy
Module-14 Data Toolkit
"""

1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


In [4]:
import numpy as np

# Create the 2x2 NumPy array with random integers between 0 and 5
arr = np.random.randint(0,6,(2,2))

print("array : \n",arr)
print("array data type : ",arr.dtype)

array : 
 [[1 3]
 [4 3]]
array data type :  int64


2. Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])

In [5]:
import numpy as np

arr = np.array([1.5, 2.6, 3.7])

arr.dtype

dtype('float64')

3. Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.


In [10]:
import numpy as np

# Create a NumPy array with three random real numbers
real_part = np.random.random(3)

# Create a NumPy array with three random imaginary parts
imaginary_part = np.random.random(3)

# Combine them to form complex numbers
arr = real_part + 1j * imaginary_part

# Ensure the data type is complex128
arr = arr.astype(np.complex128)

print("Array: \n", arr)
print("Array data type:", arr.dtype)


Array: 
 [0.77244344+0.41541492j 0.62497287+0.63876651j 0.19099653+0.14193705j]
Array data type: complex128


4. Convert an existing NumPy array 'arr' of integers to float32 data type.


In [19]:
import numpy as np

arr = np.random.randint(1,6 , (2,2))
print(f"original array: \n {arr} \n and its datatype = { arr.dtype}")

arr_f = arr.astype(np.float32)
print(f"After typecasting : \n {arr_f} \n and its datatype = {arr_f.dtype}")


original array: 
 [[3 1]
 [5 3]] 
 and its datatype = int64
After typecasting : 
 [[3. 1.]
 [5. 3.]] 
 and its datatype = float32


5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.


In [23]:
import numpy as np

arr = np.random.random(3).astype(np.float64)
print(f"original array: \n {arr} \n and its datatype = { arr.dtype}\n")

arr_f = arr.astype(np.float32)
print(f"After typecasting : \n {arr_f} \n and its datatype = {arr_f.dtype}")

original array: 
 [0.27969036 0.42471157 0.1924734 ] 
 and its datatype = float64

After typecasting : 
 [0.27969036 0.42471159 0.1924734 ] 
 and its datatype = float32


6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and datatype.

In [30]:
import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    datatype = arr.dtype
    return f"shape = {shape}, size = {size}, dataype = {datatype}"

arr = np.random.randint(1,8 , (2,3))
arr1 = np.random.random(4)

print(array_attributes(arr))
print(array_attributes(arr1))

shape = (2, 3), size = 6, dataype = int64
shape = (4,), size = 4, dataype = float64


7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [35]:
import numpy as np

def array_dimension(arr):
   
    return arr.ndim

arr = np.random.randint(1,8 , (2,3))
arr1 = np.random.random(4)

print("dimension of arr :",array_dimension(arr))
print("dimension of arr1 :",array_dimension(arr1))

dimension of arr : 2
dimension of arr1 : 1


8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.

In [40]:
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
   
    return item_size, total_size

arr = np.random.randint(1,4 , (2,3))

item_size, total_size = item_size_info(arr)
print("Item size:", item_size)
print("Total size in bytes:", total_size)

Item size: 8
Total size in bytes: 48


9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [43]:
import numpy as np

def array_strides(arr): 
     
# arr.strides returns the strides of the array.
# Strides are the number of bytes that must be skipped in memory to go to the next element along each dimension of the array.
    return arr.strides


arr = np.random.randint(1,8 , (2,3))
arr1 = np.random.random(4)

print("Array 'arr':\n", arr)
print("array stride of arr :",array_strides(arr))
# The strides of arr (a 2x3 integer array) indicate how many bytes you need
# to move in memory to go from one element to the next in each dimension.

print("\nArray 'arr1':\n", arr1)
print("array stride of arr1 :",array_strides(arr1))
# The strides of arr1 (a 1D float array) show the byte step between consecutive elements.
# Since each float64 element is 8 bytes, the stride is 8 bytes.

Array 'arr':
 [[1 1 7]
 [5 5 7]]
array stride of arr : (24, 8)

Array 'arr1':
 [0.23848997 0.07669472 0.07693454 0.71608931]
array stride of arr1 : (8,)


10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.


In [44]:
import numpy as np

def shape_stride_relationship(arr):
    
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print("Shape:", shape)
print("Strides:", strides)


Shape: (2, 3)
Strides: (12, 4)


11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.


In [3]:
import numpy as np

def create_zeros_array(n):
    arr = np.zeros(n)
    return arr
    
n = int(input("enter number: "))
create_zeros_array(n)

enter number:  6


array([0., 0., 0., 0., 0., 0.])

12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.


In [13]:
import numpy as np

def create_ones_matrix(r,c):
    arr = np.ones((r, c))
    return arr

r = int(input("enter rows: "))
c = int(input("enter column: "))

create_ones_matrix(r,c)



enter rows:  3
enter column:  4


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.


In [14]:
import numpy as np

def generate_range_array(start, stop, step):
    
    arr = np.arange(start, stop, step)
    return arr

start = int(input("Enter start value: "))
stop = int(input("Enter stop value: "))
step = int(input("Enter step value: "))

generate_range_array(start, stop, step)

Enter start value:  2
Enter stop value:  11
Enter step value:  2


array([ 2,  4,  6,  8, 10])

14. Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop` (inclusive).


In [17]:
import numpy as np

def generate_linear_space(start, stop, num):
    
    arr = np.linspace(start, stop, num)
    return arr

start = float(input("Enter start value: "))
stop = float(input("Enter stop value: "))
num = int(input("Enter step value: "))

generate_linear_space(start, stop, num)

Enter start value:  2
Enter stop value:  20
Enter step value:  10


array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.


In [18]:
import numpy as np

def create_identity_matrix(n):
    arr = np.eye(n)
    return arr

n = int(input("enter number: "))
create_identity_matrix(n)

enter number:  5


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

16. Write a function that takes a Python list and converts it into a NumPy array.


In [21]:
import numpy as np

def list_to_numpy_array(py_list):
    np_array = np.array(py_list)
    return np_array

l= [1,2,3,4,5,6,7,8,9]
list_to_numpy_array(l)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

In [1]:
import numpy as np

original_array = np.array([1, 2, 3, 4, 5])
print("Original array:", original_array)

# Step 2: Use the `view` method to create a new array object
view_array = original_array.view()
print("View array:", view_array)

# Step 3: Show that modifications to the data in one array affect the other
view_array[0] = 99
print("Modified view array:", view_array)
print("Original array after modifying view array:", original_array)

# To further demonstrate, modify the original array and check the view array
original_array[1] = 77
print("Modified original array:", original_array)
print("View array after modifying original array:", view_array)

Original array: [1 2 3 4 5]
View array: [1 2 3 4 5]
Modified view array: [99  2  3  4  5]
Original array after modifying view array: [99  2  3  4  5]
Modified original array: [99 77  3  4  5]
View array after modifying original array: [99 77  3  4  5]


18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.


In [2]:
import numpy as np

def arr_cat(arr1, arr2, axis):
    arr = np.concatenate((arr1, arr2), axis)
    return arr

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

concatenated_vertically = arr_cat(array1, array2, axis=0)
print("Concatenated vertically along axis 0:\n", concatenated_vertically)

# Concatenate along axis 1 (horizontally)
concatenated_horizontally = arr_cat(array1, array2, axis=1)
print("Concatenated horizontally along axis 1:\n", concatenated_horizontally)

Concatenated vertically along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated horizontally along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.


In [41]:
# to concatenate two NumPy arrays with different shapes horizontally (along axis 1), the arrays need to have the same number of rows.

import numpy as np


arr1 = np.array([[1, 2, 5], [3, 4, 5]]) # shape = (2,3)
arr2 = np.array([[5, 6], [7, 8]])  # shape = (2,2)

# Ensure they have the same number of rows
assert arr1.shape[0] == arr2.shape[0], " Arrays must have the same number of rows to concatenate horizontally."


arr = np.concatenate((arr1, arr2), axis = 1)
print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array horizontally:")
print(arr)


Array 1:
[[1 2 5]
 [3 4 5]]

Array 2:
[[5 6]
 [7 8]]

Concatenated array horizontally:
[[1 2 5 5 6]
 [3 4 5 7 8]]


20. Write a function that vertically stacks multiple NumPy arrays given as a list.


In [7]:
import numpy as np 

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])
arr3 = np.array([100,200,300,400])

def array_stack_vertical(l):
    return np.vstack(l)
            
    
l = [arr1, arr2, arr3]
print(array_stack_vertical(l))
#array_stack_vertical(l)

[[  1   2   3   4]
 [ 10  20  30  40]
 [100 200 300 400]]


21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.


In [10]:
import numpy as np

def array_integer(start,  stop, step):
    
    arr = np.arange(start, (stop+1), step)
    return arr

start = 2
stop = 6
step = 1

array_integer(start, stop, step)

array([2, 3, 4, 5, 6])

22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).


In [11]:
import numpy as np

def equally_spaced_array():
    arr = np.linspace(0,1,10)
    return arr

equally_spaced_array()

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).


In [14]:
import numpy as np

def log_spaced_array():
    
    arr = np.logspace(0,3,5) 
    # np.logspace(0, 3, 5) to generate 5 logarithmically spaced values between (10010^0(which is 1) and 10310^3(which is 1000)
    return arr

log_spaced_array()

array([   1.        ,    5.62341325,   31.6227766 ,  177.827941  ,
       1000.        ])

24. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.


In [1]:
import numpy as np
import pandas as pd

arr = np.random.randint(1,101,15)
arr = arr.reshape(5,3)
df = pd.DataFrame(arr, columns=['Column1', 'Column2', 'Column3'])
print(df)

   Column1  Column2  Column3
0        2       63       71
1       82       10       53
2       16        8       49
3       90        2       66
4       10       57       54


25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

In [3]:
import pandas as pd
import numpy as np

def replace_negatives_with_zeros(df, column_name):
   
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, -5]}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negatives_with_zeros(df, 'A')

print("\nDataFrame after replacing negatives in column 'A' with zeros:")
print(df)



Original DataFrame:
   A  B
0  1 -1
1 -2  2
2  3 -3
3 -4  4
4  5 -5

DataFrame after replacing negatives in column 'A' with zeros:
   A  B
0  1 -1
1  0  2
2  3 -3
3  0  4
4  5 -5


26. Access the 3rd element from the given NumPy array.

arr = np.array([10, 20, 30, 40, 50])


In [11]:
import pandas as pd
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(f"the 3rd element from the given NumPy array {arr} is = {arr[2]}")

the 3rd element from the given NumPy array [10 20 30 40 50] is = 30


27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

In [14]:
import pandas as pd
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("The element at index (1, 2) is:",arr_2d[1][2])

The element at index (1, 2) is: 6


28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])


In [20]:
import pandas as pd
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Create a boolean mask for elements greater than 5
mask = arr > 5

element = arr[mask]

print("Elements greater than 5:", element)

# arr[arr>5]

Elements greater than 5: [ 8 10  7]


29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
import pandas as pd
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print("elements from index 2 to 5 : ",arr[2:6])

elements from index 2 to 5 :  [3 4 5 6]


30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

In [1]:
import pandas as pd
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

arr_2d[0:2, 1:3]

array([[2, 3],
       [5, 6]])

31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.



In [8]:
import pandas as pd
import numpy as np

def extract_elements(arr_2d , indices):
    
    # indices[:, 0] extracts the first column from all rows.
    # indices[:, 1] extracts the second column from all rows.
    
    rows , cols = indices[: , 0] , indices[: , 1]
    elements = arr_2d[rows, cols]
    
    return elements
    

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([[0, 1],  
                    [1, 2],  
                    [2, 0]]) 

extract_elements(arr_2d , indices)

array([2, 6, 7])

32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.


In [11]:
import pandas as pd
import numpy as np

def filter_elements(arr, threshold):
    print(arr>threshold)
    ar = arr[arr>threshold]
    return ar
    
arr = np.array([1,2,4,5,89,56,78,456,456,24,9,676,868,959,506])
threshold = 10

filter_elements(arr, threshold)


[False False False False  True  True  True  True  True  True False  True
  True  True  True]


array([ 89,  56,  78, 456, 456,  24, 676, 868, 959, 506])

33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.


In [18]:
import pandas as pd
import numpy as np

def extract_ele_dim(arr_3d, indices_0, indices_1, indices_2):
    
    # Ensure the indices arrays are NumPy arrays
    indices_0 = np.array(indices_0)
    indices_1 = np.array(indices_1)
    indices_2 = np.array(indices_2)
    
    # Use advanced indexing to extract the elements
    extracted_elements = arr_3d[indices_0, indices_1, indices_2]
    
    return extracted_elements 
    
arr_3d = np.random.randint(1,10 , (3,3,3))

indices_0 = [0, 1, 2]
indices_1 = [1, 2, 0]
indices_2 = [2, 0, 1]

print("3D-Array : \n",arr_3d)
print("\nextracted elements: \n",extract_ele_dim(arr_3d, indices_0, indices_1, indices_2))

3D-Array : 
 [[[5 7 1]
  [5 4 1]
  [9 1 9]]

 [[1 5 7]
  [6 3 2]
  [7 3 6]]

 [[7 3 1]
  [9 8 8]
  [7 7 5]]]

extracted elements: 
 [1 7 3]


34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.


In [19]:
import pandas as pd
import numpy as np

def filter_ele_two_condition(arr, condition1, condition2):
    
    elements = arr[condition1(arr) & condition2(arr)]
    return elements

arr = np.array([1,10,2,20,3,30,4,40,5,50,90,100,597,235, 467,4456, 456, 156])

condition1 = lambda x: x>50
condition2 = lambda x: x<500
filter_ele_two_condition(arr, condition1, condition2)

array([ 90, 100, 235, 467, 456, 156])

35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.


In [24]:
import pandas as pd
import numpy as np

def extract_ele_sep_arr(arr,indices_r , indices_c):
    elements = arr[indices_r, indices_c]
    return elements
    
arr_2d = np.random.randint(1,10 , (3,3))    
indices_r = np.array([0,1,2])
indices_c = np.array([2,1,0])
print("2D Array:\n",arr_2d)
print("\nExtracted Elements :\n",extract_ele_sep_arr(arr_2d, indices_r, indices_c))

2D Array:
 [[2 1 3]
 [9 3 2]
 [5 1 2]]

Extracted Elements :
 [3 3 5]


36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.


In [25]:
import pandas as pd
import numpy as np

arr = np.random.randint(1,10, (3,3)) 
print("Original Array:\n",arr)

print("\n New Array:\n",arr+5)

Original Array:
 [[9 4 2]
 [8 7 7]
 [5 6 7]]

 New Array:
 [[14  9  7]
 [13 12 12]
 [10 11 12]]


37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.


In [38]:
import pandas as pd
import numpy as np

arr1 = np.random.randint(1,10, (1,3)) 
#print("Original Array-1:\n",arr1)

reshape_arr = arr1.T
arr2 = np.random.randint(1,10, (3,4))
print(f"arr1 =>\n{reshape_arr} \n arr2=>\n{arr2}")
#print("Original Array-2:\n",arr2)

print("\n New Array:\n",arr2 * reshape_arr)

arr1 =>
[[3]
 [9]
 [3]] 
 arr2=>
[[3 4 1 7]
 [3 3 8 7]
 [2 1 1 2]]

 New Array:
 [[ 9 12  3 21]
 [27 27 72 63]
 [ 6  3  3  6]]


38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.


In [42]:
import pandas as pd
import numpy as np

arr1 = np.random.randint(1,10, (1,4)) 

reshape_arr = arr1.T
arr2 = np.random.randint(1,10, (4,3))
print(f"arr1 =>\n{reshape_arr} \n arr2=>\n{arr2}")

print("\n New Array:\n",arr2 + reshape_arr)

arr1 =>
[[5]
 [8]
 [6]
 [4]] 
 arr2=>
[[1 7 8]
 [9 2 7]
 [4 8 1]
 [6 6 1]]

 New Array:
 [[ 6 12 13]
 [17 10 15]
 [10 14  7]
 [10 10  5]]


39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.


In [43]:
import pandas as pd
import numpy as np

arr1 = np.random.randint(1,10, (1,4)) 

reshape_arr = arr1.reshape(4,1)
arr2 = np.random.randint(1,10, (4,3))
print(f"arr1 =>\n{reshape_arr} \n arr2=>\n{arr2}")

print("\n New Array:\n",arr2 + reshape_arr)

arr1 =>
[[5]
 [9]
 [3]
 [2]] 
 arr2=>
[[2 4 7]
 [3 4 3]
 [9 8 6]
 [7 4 1]]

 New Array:
 [[ 7  9 12]
 [12 13 12]
 [12 11  9]
 [ 9  6  3]]


40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

In [45]:
"""import pandas as pd
import numpy as np

arr1 = np.random.randint(1,10, (2,3)) 

reshape_arr = arr1.reshape(3,2)
arr2 = np.random.randint(1,10, (2,2))
print(f"arr1 =>\n{reshape_arr} \n arr2=>\n{arr2}")

print("\n New Array:\n", reshape_arr@arr2 )
"""

arr1 =>
[[7 5]
 [9 4]
 [3 7]] 
 arr2=>
[[4 3]
 [7 9]]

 New Array:
 [[63 66]
 [64 63]
 [61 72]]


In [47]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
arr2 = np.array([[2, 3], [4, 5]])        # Shape (2, 2)

# Reshape arr2 to align its dimensions with arr1 for broadcasting
arr2_reshaped = np.expand_dims(arr2, axis=2)  # Shape (2, 2, 1)

# Perform multiplication using broadcasting
result = arr1 * arr2_reshaped

print(f"arr1 =>\n{arr1} \n arr2=>\n{arr2_reshaped}")
print("Result:\n", result)


arr1 =>
[[1 2 3]
 [4 5 6]] 
 arr2=>
[[[2]
  [3]]

 [[4]
  [5]]]
Result:
 [[[ 2  4  6]
  [12 15 18]]

 [[ 4  8 12]
  [20 25 30]]]


41. Calculate column wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [12]:
import pandas as pd
import numpy as np

"""
print("Array :\n", arr)
col1 = arr[:,0]
col2 = arr[:,1]
col3 = arr[:,2]

print("\n",col1.mean())
print("\n",col2.mean())
print("\n",col3.mean())
"""
arr = np.array([[1, 2, 3], [4, 5, 6]])

col_mean = np.mean(arr, axis=0)

print("Array:\n", arr)
print("\nColumn-wise mean:\n", col_mean)


Array:
 [[1 2 3]
 [4 5 6]]

Column-wise mean:
 [2.5 3.5 4.5]


42. Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
import pandas as pd
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

max_value = np.max(arr, axis=1 )
print(max_value)

[3 6]


43. For the given array, find indices of maximum value in each column.

arr = np.array([[1, 2, 3], [4, 5, 6]])

In [15]:
import pandas as pd
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_indices = np.argmax(arr, axis=0)

print("Array:\n", arr)
print("\nIndices of maximum values in each column:\n", max_indices)

Array:
 [[1 2 3]
 [4 5 6]]

Indices of maximum values in each column:
 [1 1 1]


44. For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])


In [18]:
import pandas as pd
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", arr)

def moving_sum(arr, window_size):
    # Get the shape of the array
    rows, cols = arr.shape
    
    # Initialize an output array with the same shape as the input
    result = np.zeros((rows, cols - window_size + 1))
    
    # Compute the moving sum for each row
    for i in range(rows):
        for j in range(cols - window_size + 1):
            result[i, j] = np.sum(arr[i, j:j + window_size])
    
    return result

# Define the window size
window_size = 2

# Apply the custom moving sum function
moving_sum_result = moving_sum(arr, window_size)

print("\nMoving sum along rows with window size {}:\n{}".format(window_size, moving_sum_result))

Array:
 [[1 2 3]
 [4 5 6]]

Moving sum along rows with window size 2:
[[ 3.  5.]
 [ 9. 11.]]


45. In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

In [2]:
import pandas as pd
import numpy as np

arr = np.array([[2, 4, 6], [3, 5, 7]])

even_mask = (arr % 2 == 0)

# Check if all elements in each column are even
all_even_in_columns = np.all(even_mask, axis=0)
# np.all()>>>> Test whether all array elements along a given axis evaluate to True.

print("Array:\n", arr)
print("\nEven mask:\n", even_mask)
print("\nAll elements in each column are even:\n", all_even_in_columns)
    

Array:
 [[2 4 6]
 [3 5 7]]

Even mask:
 [[ True  True  True]
 [False False False]]

All elements in each column are even:
 [False False False]


46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

In [30]:
import pandas as pd
import numpy as np

def reshaped_matrix(arr, m , n):
    if arr.size != m * n :
        raise ValueError("The total number of elements does not match the specified shape.")
    reshaped_arr = np.reshape(arr , (m , n))
    return reshaped_arr

        
original_array = np.array([1, 2, 3, 4, 5, 6])
print("Original array :\n",original_array)
m , n = 2 , 3

print("reshaped array :\n",reshaped_matrix(original_array , m , n))

Original array :
 [1 2 3 4 5 6]
reshaped array :
 [[1 2 3]
 [4 5 6]]


47. Create a function that takes a matrix as input and returns the flattened array
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
import pandas as pd
import numpy as np

def flat_arr(arr):
    size = arr.size
    arr1 = np.reshape(arr, size)
    return arr1

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
flat_arr(input_matrix)


array([1, 2, 3, 4, 5, 6])

In [36]:
# Another approach

import numpy as np

def flat_arr(arr):
    # Flatten the array using np.flatten()
    return arr.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

print("Input matrix:\n", input_matrix)
print("\nFlattened array:\n", flat_arr(input_matrix))


Input matrix:
 [[1 2 3]
 [4 5 6]]

Flattened array:
 [1 2 3 4 5 6]


48. Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])


In [38]:
import pandas as pd
import numpy as np

array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

res_r = np.concatenate((array1 , array2) , axis=0 )
res_c = np.concatenate((array1 , array2) , axis=1 )
print("concat along rows:\n",res_r)
print("\nconcat along column : \n",res_c)

concat along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

concat along column : 
 [[1 2 5 6]
 [3 4 7 8]]


49. Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [39]:
import pandas as pd
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def split_array(arr, num_splits, axis=0):
    
    try:
        sub_arrays = np.array_split(arr, num_splits, axis=axis)
        return sub_arrays
    except ValueError as e:
        print(f"Error: {e}")
        return None

num_splits = 3  
axis = 0 

sub_arrays = split_array(original_array, num_splits, axis)

print("Original array:\n", original_array)
print("\nSub-arrays after splitting along axis {}:\n".format(axis))
for i, sub_array in enumerate(sub_arrays):
    print(f"Sub-array {i+1}:\n{sub_array}\n")

Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Sub-arrays after splitting along axis 0:

Sub-array 1:
[[1 2 3]]

Sub-array 2:
[[4 5 6]]

Sub-array 3:
[[7 8 9]]



50. Write a function that inserts and then deletes elements from a given array at specified indices.

original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

In [40]:
import pandas as pd
import numpy as np

def insert_and_delete_elements(arr, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    for index, value in zip(indices_to_insert, values_to_insert):
        arr = np.insert(arr, index, value)
    
    # Update indices to delete after insertions
    adjusted_indices_to_delete = np.array(indices_to_delete)
    for insert_index in sorted(indices_to_insert):
        adjusted_indices_to_delete[adjusted_indices_to_delete >= insert_index] += 1
    
    # Delete elements at specified indices
    arr = np.delete(arr, adjusted_indices_to_delete)
    
    return arr

original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Perform the insertions and deletions
result_array = insert_and_delete_elements(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Original array:", original_array)
print("Resulting array:", result_array)



Original array: [1 2 3 4 5]
Resulting array: [ 1 10  3 11  5]


51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

In [13]:
import pandas as pd
import numpy as np

arr1 = np.random.randint(1,10, size = 10)
arr2 = np.arange(1,11)

print(f"array 1 : \n {arr1}  \narray 2 : \n {arr2}")
print("\nelement-wise addition: \n", arr1 + arr2)

array 1 : 
 [6 6 5 4 1 3 7 8 4 5]  
array 2 : 
 [ 1  2  3  4  5  6  7  8  9 10]

element-wise addition: 
 [ 7  8  8  8  6  9 14 16 13 15]


52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [17]:
import pandas as pd
import numpy as np

arr1 = np.arange(10, 0, -1)
arr2 = np.random.randint(1,11, size=10)

print(f"array 1 : \n {arr1}  \narray 2 : \n {arr2}")
print("\nelement-wise subtraction: \n", arr2 - arr1)

array 1 : 
 [10  9  8  7  6  5  4  3  2  1]  
array 2 : 
 [ 8 10  3 10 10  5  9  3  9  2]

element-wise subtraction: 
 [-2  1 -5  3  4  0  5  0  7  1]


53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.

In [20]:
import pandas as pd
import numpy as np

arr1 = np.arange(1,6)
arr2 = np.random.randint(1,10, size=5)

print(f"array 1 : \n {arr1}  \narray 2 : \n {arr2}")
print("\nelement-wise multiplication: \n", arr2 * arr1)

array 1 : 
 [1 2 3 4 5]  
array 2 : 
 [4 9 9 1 4]

element-wise subtraction: 
 [ 4 18 27  4 20]


54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.

In [22]:
import pandas as pd
import numpy as np

arr1 = np.arange(2,11, 2)
arr2 = np.arange(1,6)

print(f"array 1 : \n {arr1}  \narray 2 : \n {arr2}")
print("\nelement-wise division: \n", arr2 / arr1)

array 1 : 
 [ 2  4  6  8 10]  
array 2 : 
 [1 2 3 4 5]

element-wise division: 
 [0.5 0.5 0.5 0.5 0.5]


55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [24]:
import pandas as pd
import numpy as np

arr1 = np.arange(1,6)
arr2 = np.arange(5,0,-1)

print(f"array 1 : \n {arr1}  \narray 2 : \n {arr2}")
print("\nelement-wise exponentiation: \n", arr1 ** arr2)

array 1 : 
 [1 2 3 4 5]  
array 2 : 
 [5 4 3 2 1]

element-wise exponentiation: 
 [ 1 16 27 16  5]


56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [26]:
import pandas as pd
import numpy as np

def count_substring(arr, substring):
    # Check if the array contains only strings
    if not np.issubdtype(arr.dtype, np.str_):
        raise ValueError("The array should contain only strings")
    
    # Apply vectorized count of substring in each element of the array
    count_array = np.char.count(arr, substring)
    
    # Sum the counts to get the total occurrences
    total_count = np.sum(count_array)
    
    return total_count

arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
print(f"The substring '{substring}' occurs {count_substring(arr, substring)} times in the array.")


The substring 'hello' occurs 3 times in the array.


57. Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [31]:
import pandas as pd
import numpy as np

def extract_upercase(arr):
    if not np.issubdtype(arr.dtype, np.str_):
        raise ValueError("The array should contain only strings")
    
    # Extract uppercase characters for each string in the array
    uppercase_chars = np.array([''.join([char for char in string if char.isupper()]) for string in arr])
    
    return uppercase_chars

# Example usage
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
print("Original array:\n", arr)
uppercase_chars = extract_upercase(arr)
print("Uppercase characters extracted:\n", uppercase_chars)


Original array:
 ['Hello' 'World' 'OpenAI' 'GPT']
Uppercase characters extracted:
 ['H' 'W' 'OAI' 'GPT']


58. Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [1]:
import pandas as pd
import numpy as np

def replace_occurence(arr, old_substring, new_substring):
    
    if not np.issubdtype(arr.dtype , np.str_):
        raise ValueError("The array should contain only strings") 
        
    replaced_array = np.char.replace(arr, old_substring, new_substring)
    return replaced_array

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'fruit'
print("Original array:\n", arr)
print("Array after replacement:\n", replace_occurence(arr, old_substring, new_substring))


Original array:
 ['apple' 'banana' 'grape' 'pineapple']
Array after replacement:
 ['fruit' 'banana' 'grape' 'pinefruit']


59. Write a function that concatenates strings in a NumPy array element-wise.

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

In [4]:
import pandas as pd
import numpy as np

def str_concat(s1, s2):
    if not (np.issubdtype(arr1.dtype, np.str_) and np.issubdtype(arr2.dtype, np.str_)):
        raise ValueError("Both arrays should contain only strings")
    if arr1.shape != arr2.shape:
        raise ValueError("Both arrays must have the same shape")
        
    result = np.char.add(arr1, arr2)
    return result

arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Concatenated array:\n",str_concat(arr1, arr2))

Array 1:
 ['Hello' 'World']
Array 2:
 ['Open' 'AI']
Concatenated array:
 ['HelloOpen' 'WorldAI']


60. Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [11]:
import pandas as pd
import numpy as np

def str_len(arr):
    
    if not np.issubdtype(arr.dtype , np.str_):
        raise ValueError("array must contain all strings")
        
     # Use np.vectorize to apply the len function to each element in the array
    vectorized_len = np.vectorize(len)
    lengths = vectorized_len(arr)
    
    # Find and return the maximum length
    max_length = np.max(lengths)
    max_length_index = np.argmax(lengths)
    
    # Get the longest string and its length
    longest_string = arr[max_length_index]
    
    return max_length, longest_string

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
print("Array:\n", arr)
print("Length of the longest string:",str_len(arr))

Array:
 ['apple' 'banana' 'grape' 'pineapple']
Length of the longest string: (9, 'pineapple')


61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

In [16]:
import pandas as pd
import numpy as np

data = np.random.randint(1, 1001, size=100)
print("data :\n",data)

print("\nMean : ",np.mean(data))
print("\nMedian : ",np.median(data))
print("\nVariance : ",np.var(data))
print("\nstandard deviation : ",np.std(data))

data :
 [ 701  351  470  552  720  964  256  975  370  828  822  154   27   21
  154  521  491  786  325  455  791  117   43  492  423  505  696  569
  835  392  713  453  277  322  791  311  933  761  681  849  682  560
  192  629   82  712   62  566  119  224  415  369  896 1000  462  637
  802  321  295  814   19   23  470  786  193   59  665  218  470  750
  467  989  584  868  873  546  649  554  516  795  907  373  930  893
  361  456  916  886  874  333   95  313  328  931  655  951  764  189
  949  431]

Mean :  537.65

Median :  533.5

Variance :  79661.7475

standard deviation :  282.2441274854093


62. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

In [18]:
import pandas as pd
import numpy as np

data = np.random.randint(1, 101, size=50)
print("data :\n",data)

print("\n25th percentile : ",np.percentile(data, 25))
print("\n75th percentile : ",np.percentile(data, 75))

data :
 [ 76  87  65  49  22  55  82  83  81  26  64  29  94  49  54  25  36  35
  66  19  44  48  69  32  32   1  91   1  30  26  34   8  31  68  43  67
  20  59  65  75  44  72 100  37  14  71  45  33  30  61]

25th percentile :  30.25

75th percentile :  67.75


63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

In [19]:
import numpy as np
import pandas as pd

array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([2, 3, 4, 5, 6])

# Compute the correlation coefficient between the arrays
correlation_coefficient = np.corrcoef(array1, array2)[0, 1]
print("Correlation Coefficient:", correlation_coefficient)

Correlation Coefficient: 0.9999999999999999


64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.


In [20]:
import numpy as np
import pandas as pd

matrix1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

result_matrix = np.dot(matrix1, matrix2)

print("Matrix 1:\n", matrix1)
print("\nMatrix 2:\n", matrix2)
print("\nResult of Matrix Multiplication:\n", result_matrix)

Matrix 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix 2:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Result of Matrix Multiplication:
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

In [10]:
import numpy as np
import pandas as pd

arr = np.random.randint(10, 1001, size=50)
print("Original array :\n",arr)
print("\n10th percentile:", np.percentile(arr,10))
print("\n25th percentile (Q1):", np.percentile(arr,25))
print("\n50th (median) percentile:", np.percentile(arr,50))
print("\n75th percentile (Q3):", np.percentile(arr,75))
print("\n90th percentile:", np.percentile(arr,90))


Original array :
 [665 364 884 194 781  50 467 261 176  16 202 689 361 388  94 809 715 737
 199 865 373 143 904 539  51 217 889 970 857 309 385 159 647 757 212  68
 271  48 323 265  18 196 526 975 939 663  28 671 204 605]

10th percentile: 50.9

25th percentile (Q1): 196.75

50th (median) percentile: 368.5

75th percentile (Q3): 708.5

90th percentile: 884.5


66. Create a NumPy array of integers and find the index of a specific element.

In [6]:
import numpy as np
import pandas as pd

array = np.random.randint(1,100, size=50)
print("array \n",array)

element_to_find = array[20]  

# Find the index of the specified element
index = np.where(array == element_to_find)[0]

if index.size > 0:
    print(f"The index of the element {element_to_find} is: {index[0]}")
else:
    print(f"The element {element_to_find} is not in the array.")


array 
 [60 17 58 25 31 27 77 11 71 92 99 92 69 33 43  2 52 99 18 62 11 42 76 79
 97 74 26  9 33 40 24 25 19 50 82 33 19 35 13 56  6 80 58 90 54 77 34 31
 20  5]
The index of the element 11 is: 7


67. Generate a random NumPy array and sort it in ascending order.

In [10]:
import numpy as np
import pandas as pd

array = np.random.randint(1,100, size=20)
print("array \n",array)

print("sorted array :\n",np.sort(array))


array 
 [94 70 34  9 51 93 99 14 32 26 67 97 35 68 98 57 91 36 85 72]
sorted array :
 [ 9 14 26 32 34 35 36 51 57 67 68 70 72 85 91 93 94 97 98 99]


68. Filter elements >20  in the given NumPy array.

arr = np.array([12, 25, 6, 42, 8, 30])

In [14]:
import numpy as np
import pandas as pd

arr = np.array([12, 25, 6, 42, 8, 30])
print("original array: \n",arr)
filter_arr= arr[arr>20]
print("filter array > 20:\n",filter_arr)

original array: 
 [12 25  6 42  8 30]
filter array > 20:
 [25 42 30]


69. Filter elements which are divisible by 3 from a given NumPy array
arr = np.array([1, 5, 8, 12, 15])

In [16]:
import numpy as np
import pandas as pd

arr = np.array([1, 5, 8, 12, 15])
print("original array: \n",arr)
mask = arr % 3 == 0 
filter_arr= arr[mask]
print("filter array divisible by 3 :\n",filter_arr)

original array: 
 [ 1  5  8 12 15]
filter array divisible by 3 :
 [12 15]


70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array
arr = np.array([10, 20, 30, 40, 50])

In [20]:
import numpy as np
import pandas as pd

arr = np.array([10, 20, 30, 40, 50])
print("original array: \n",arr)
mask = (arr >= 20) & (arr <= 40) 
filter_arr= arr[mask]
print("filter array which are ≥ 20 and ≤ 40 :\n",filter_arr)

original array: 
 [10 20 30 40 50]
filter array which are ≥ 20 and ≤ 40 :
 [20 30 40]


71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.

arr = np.array([1, 2, 3])

In [21]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte order of the array:", byte_order)

Byte order of the array: =


72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [22]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

# Perform byte swapping in place
arr.byteswap(True)

# Print the byte-swapped array and its byte order
print("Byte-swapped array:", arr)
print("Byte-swapped byte order:", arr.dtype.byteorder)


Original array: [1 2 3]
Original byte order: =
Byte-swapped array: [16777216 33554432 50331648]
Byte-swapped byte order: =


73. For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)

In [23]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

# Swap the byte order without modifying the original array
swapped_arr = arr.byteswap().newbyteorder()

# Print the byte-swapped array and its byte order
print("Byte-swapped array:", swapped_arr)
print("Byte-swapped byte order:", swapped_arr.dtype.byteorder)

# Verify the original array remains unchanged
print("Original array after byte swap operation:", arr)

Original array: [1 2 3]
Original byte order: =
Byte-swapped array: [1 2 3]
Byte-swapped byte order: >
Original array after byte swap operation: [1 2 3]


74. For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.

arr = np.array([1, 2, 3], dtype=np.int32)


In [24]:
import numpy as np
import pandas as pd

arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original array:", arr)
print("Original byte order:", arr.dtype.byteorder)

# Check the system's byte order
if arr.dtype.byteorder == '=':  # Native byte order
    import sys
    system_byteorder = sys.byteorder
    if system_byteorder == 'little':
        target_byteorder = '>'
    else:
        target_byteorder = '<'
else:
    target_byteorder = arr.dtype.byteorder

# Swap the byte order conditionally
swapped_arr = arr.newbyteorder(target_byteorder)

# Print the byte-swapped array and its byte order
print("Conditionally byte-swapped array:", swapped_arr)
print("Byte-swapped byte order:", swapped_arr.dtype.byteorder)

# Verify the original array remains unchanged
print("Original array after byte swap operation:", arr)


Original array: [1 2 3]
Original byte order: =
Conditionally byte-swapped array: [16777216 33554432 50331648]
Byte-swapped byte order: >
Original array after byte swap operation: [1 2 3]


75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype` attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

In [40]:
"""
In NumPy, you can check if byte swapping is necessary by examining the byteorder attribute of the array's data type (dtype). 
The byteorder attribute indicates the byte order (endianness) of the data type.
Here are the possible values for byteorder and their meanings:

'=' : Native byte order (depends on the system).
'<' : Little-endian.
'>' : Big-endian.
'|' : Not applicable (for non-numeric types).
To determine if byte swapping is necessary, 
you can compare the byteorder attribute of the array's dtype with the native byte order of the current system.
"""

import numpy as np
import pandas as pd

arr = np.array([1, 2, 3], dtype=np.int32)
print("Original array :\n", arr)

# Get the byte order of the array's dtype
byte_order = arr.dtype.byteorder
print("Byte order of the array's dtype:", byte_order)

# Determine the native byte order of the system
native_byte_order = '=' if np.little_endian else '>'

# Check if byte swapping is necessary
if byte_order == '=':
    print("Byte swapping is not necessary as the array is in native byte order.")
elif (byte_order == '<' and np.little_endian) or (byte_order == '>' and not np.little_endian):
    print("Byte swapping is not necessary as the array is in the correct byte order for this system.")
else:
    print("Byte swapping is necessary to match the system's native byte order.")

Original array :
 [1 2 3]
Byte order of the array's dtype: =
Byte swapping is not necessary as the array is in native byte order.


76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [29]:
import numpy as np
import pandas as pd

arr1 = np.random.randint(1,11, size=6)
print("Original array :\n", arr1)

copy_arr = np.copy(arr1)
copy_arr[0] = 1000
print("\n copy_arr \n",copy_arr)

print("\nOriginal array after modification:\nNo, it does not affect the orig arr\n", arr1)

Original array :
 [2 8 9 1 3 2]

 copy_arr 
 [1000    8    9    1    3    2]

Original array after modification:
No, it does not affect the orig arr
 [2 8 9 1 3 2]


77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [37]:
import numpy as np
import pandas as pd

array_a = np.random.randint(1,10,(3,3))
print("Original array :\n", array_a)

view_slice = array_a[1:3 , :]
view_slice[0,0] = 1000
print("\nview_slice array:\n",view_slice)
print("\nOriginal array after modification:\nYes, it changes the original array \n", array_a)


Original array :
 [[7 1 5]
 [4 6 4]
 [2 3 5]]

view_slice array:
 [[1000    6    4]
 [   2    3    5]]

Original array after modification:
Yes, it changes the original array 
 [[   7    1    5]
 [1000    6    4]
 [   2    3    5]]


78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [16]:
import numpy as np
import pandas as pd

array_a = np.arange(1, 13).reshape(4,3)
print("Original array :\n", array_a)

#view_b = array_a[1:4 , 1:3] + 5 # this does not affect the orignl arr coz it will create new array
view_b = array_a[1:4 , 1:3]
view_b += 5  # This modifies the original array
print("\nview_b array \n",view_b)
print("\nOriginal array after modification :\n Yes, it affects the original array\n", array_a)

Original array :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

view_b array 
 [[10 11]
 [13 14]
 [16 17]]

Original array after modification :
 Yes, it affects the original array
 [[ 1  2  3]
 [ 4 10 11]
 [ 7 13 14]
 [10 16 17]]


79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.

In [39]:
import numpy as np
import pandas as pd

orig_array = np.random.randint(1,8, (2,4))
print("Original array :\n", orig_array)

reshaped_view = np.reshape(orig_array , (4,2))
print("Reshaped array : \n",reshaped_view)

reshaped_view[0,0] = 1000
print("Original array after modification:\n", orig_array)


Original array :
 [[3 3 7 4]
 [7 2 4 7]]
Reshaped array : 
 [[3 3]
 [7 4]
 [7 2]
 [4 7]]
Original array after modification:
 [[1000    3    7    4]
 [   7    2    4    7]]


80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [33]:
import numpy as np
import pandas as pd

data = np.random.randint(1,10, (3,4))
print("Original array :\n", data)

data_copy = data[data>5].copy()
print("Copied array :\n", data_copy)

data_copy[0]=1000
print("Modification :\n", data_copy )
print("Original array after modification:\n", data)

Original array :
 [[8 2 7 8]
 [5 8 4 4]
 [4 7 8 5]]
Copied array :
 [8 7 8 8 7 8]
Modification :
 [1000    7    8    8    7    8]
Original array after modification:
 [[8 2 7 8]
 [5 8 4 4]
 [4 7 8 5]]


81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

In [23]:
import numpy as np

A = np.random.randint(0, 10, size=(3, 3))  
B = np.random.randint(0, 10, size=(3, 3))

print("original matrix A : \n", A)
print("original matrix B : \n", B)

print("Addition :\n", A+B)
print("Subtracion \n:", A-B)


original matrix A : 
 [[0 2 9]
 [7 1 6]
 [4 9 2]]
original matrix B : 
 [[5 3 2]
 [0 8 7]
 [3 0 6]]
Addition :
 [[ 5  5 11]
 [ 7  9 13]
 [ 7  9  8]]
Subtracion 
: [[-5 -1  7]
 [ 7 -7 -1]
 [ 1  9 -4]]


82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [7]:
import numpy as np

c = np.random.rand(3,2)
d = np.random.rand(2,4)

r = np.dot(c, d)
np.round(r, 3)

array([[0.081, 0.658, 0.677, 0.397],
       [0.078, 0.526, 0.648, 0.733],
       [0.11 , 0.803, 0.914, 0.823]])

83. Create a matrix `E` and find its transpose.

In [11]:
import numpy as np

E = np.random.rand(2,2)
print("original matrix: \n", np.round(E,2))
mat = E.T
print("\ntransposed matrix: \n", np.round(mat,2))

original matrix: 
 [[0.02 0.03]
 [0.55 0.01]]

transposed matrix: 
 [[0.02 0.55]
 [0.03 0.01]]


84. Generate a square matrix `F` and compute its determinant.

In [13]:
import numpy as np

F = np.random.rand(2,2)
print("original matrix: \n", np.round(E,2))

mat = np.linalg.det(F)
print("\ndeterminant of  matrix: \n", np.round(mat,2))

original matrix: 
 [[0.02 0.03]
 [0.55 0.01]]

determinant of  matrix: 
 0.57


85. Create a square matrix `G` and find its inverse

In [18]:
import numpy as np

G = np.random.rand(4,4)
print("original matrix: \n", np.round(G,2))

mat = np.linalg.inv(G)
print("\nInverse of  matrix: \n", np.round(mat,2))

original matrix: 
 [[0.91 0.83 0.46 0.29]
 [0.87 0.03 0.43 0.58]
 [0.83 0.85 0.31 0.8 ]
 [0.99 0.94 0.5  0.69]]

Inverse of  matrix: 
 [[ 5.16  1.33  4.9  -8.98]
 [ 0.11 -1.26  0.05  0.96]
 [-6.42 -0.48 -9.81 14.5 ]
 [-2.94  0.16 -0.04  2.6 ]]
